services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/share/traefik/traefik.yml:/traefik.yml:ro
      - /usr/share/traefik/data/acme.json:/data/acme.json
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`proxy.strg-c.de`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      # BasicAuth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${DASHBOARD_USERS}"

networks:
  traefik:
    external: true
